### ISSUE TITLE
compile error: The module `gleam/dict` does not have a `update` value.

### ISSUE THREAD

**Issue by PegasusPlusUS** [giacomocavalieri/tote#2]
error: Unknown module value
    ┌─ c:\Users\pegas\source\repos\PegasusPlusUS\Study\zigzag\gleam\zigzag.gleam\build\packages\tote\src\tote\bag.gleam:151:13
    │
151 │         dict.update(bag.map, item, fn(n) { option.unwrap(n, or: 0) + to_add }),
    │             ^^^^^^^

The module `gleam/dict` does not have a `update` value.

**Comment by giacomocavalieri** [comment]
Thank you! I've released v1.0.2 fixing this issue
